# Generated by Django 4.1 on 2022-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
