# Generated by Django 4.1 on 2022-09-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_pages', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Edukativni kutak'},
        ),
    ]
