# Generated by Django 4.1 on 2022-09-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_pages', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
