# Generated by Django 4.1 on 2022-09-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_pages', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Članak', 'verbose_name_plural': 'Članci'},
        ),
    ]
