# Generated by Django 4.1 on 2022-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_pages', '0006_rename_published_post_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.IntegerField(default=10),
        ),
    ]
