# Generated by Django 4.2.26 on 2026-10-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('slug', models.SlugField(default='')),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Edukacija stručnjaka',
                'verbose_name_plural': 'Edukacije stručnjaka',
            },
        ),
    ]
