# Generated by Django 4.1 on 2022-10-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_associate_alter_teammember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='position',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.IntegerField(default=10),
        ),
    ]
