# Generated by Django 4.1 on 2022-10-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_and_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratelist',
            options={'verbose_name': 'Cjenik'},
        ),
    ]
