# Generated by Django 4.2.26 on 2026-09-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_and_rates', '0003_alter_ratelist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratelink_url', models.URLField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sidreni cjenik',
                'verbose_name_plural': 'Sidreni cjenik',
            },
        ),
    ]
