# Generated by Django 4.1 on 2022-10-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivinggroup',
            name='image',
        ),
        migrations.RemoveField(
            model_name='drivinggroup',
            name='title',
        ),
        migrations.RemoveField(
            model_name='drivingindividual',
            name='image',
        ),
        migrations.RemoveField(
            model_name='drivingindividual',
            name='title',
        ),
    ]
